---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  macos:
    name: macOS / Idris2 latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          set -euxo pipefail
          brew install gmp llvm lld
          echo "$(brew --prefix llvm)/bin" >> "$GITHUB_PATH"
          echo "$(brew --prefix lld)/bin" >> "$GITHUB_PATH"
          export PATH="$(brew --prefix lld)/bin:$(brew --prefix llvm)/bin:$PATH"
          uname -a
          uname -m
      - name: Build and install Chez Scheme
        run: |
          set -euxo pipefail
          git clone --depth=1 \
            https://github.com/cisco/ChezScheme.git \
            /tmp/ChezScheme
          cd /tmp/ChezScheme
          ./configure \
            --threads \
            --installprefix="$HOME/.local"
          make -j"$(sysctl -n hw.ncpu)"
          make install
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.local/bin:$PATH"
      - name: Install Idris2 and Pack
        run: |
          set -euxo pipefail
          export PATH="$HOME/.local/bin:$PATH"
          git clone --depth=1 \
            https://github.com/stefan-hoeck/idris2-pack.git \
            /tmp/idris2-pack
          cd /tmp/idris2-pack
          make micropack SCHEME=scheme
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.local/bin:$PATH"
          rm -rf /tmp/idris2-pack
      - name: Build async-kqueue
        run: |
          set -euxo pipefail
          export PATH="$HOME/.local/bin:$PATH"
          pack --no-prompt cleanbuild
      - name: Build tests
        run: |
          set -euxo pipefail
          export PATH="$HOME/.local/bin:$PATH"
          cd test
          pack --no-prompt cleanbuild
      - name: Run tests
        run: |
          set -euxo pipefail
          export PATH="$HOME/.local/bin:$PATH"
          cd test
          export DYLD_LIBRARY_PATH="$(pack libs-path)"
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"
          pack run
